name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure the run
      run: cp .env.template .env
    - name: Build the Docker Salad operator and client
      run: |
        pwd
        ls
        export BRANCH_NAME="$(echo $GITHUB_REF | grep -o '[^/]\+$')"
        git clone https://github.com/enigmampc/docker-environment
        cd docker-environment
        make clone-salad BRANCH=$BRANCH_NAME
        make clone-contract
        # make build-salad-operator DOCKER_TAG=develop
        # make build-salad-client DOCKER_TAG=develop
    - name: Launch network and run the tests
      run: |
        pwd
        ls
        docker-compose -f docker-compose.yml -f docker-compose.salad.yml up &
        TIMEOUT=250 # timeout in seconds
        NOW=$(date +%s)
        until docker-compose -f docker-compose.yml -f docker-compose.salad.yml logs --tail 1000 salad_client | grep -m 1 "You may start running tests" || [ $(( $(date +%s) - $NOW )) -gt $TIMEOUT ]; do
            sleep 1
        done
        if [ $(( $(date +%s) - $NOW )) -gt $TIMEOUT ]; then
            exit 1
        fi
        docker-compose -f docker-compose.yml -f docker-compose.salad.yml exec -T salad_client yarn test
